FROM openjdk:8u171-jre-alpine
#instalar la utilidad bash
RUN apk add --no-cache bash

#setea el directorio de trabajo
WORKDIR /opt

#copia el archivo compilado (por maven) adentro de la imagen en /opt
COPY target/ejemplo-uber-jar.jar .

#esto no es importante (solo de ejemplo como pasar la linea de comando)
ENV JAVA_OPTS="-Xms32m -Xmx128m"

#Esto esto que ejecuta el contenedor cuando inicia
ENTRYPOINT exec java $JAVA_OPTS -jar ejemplo-uber-jar.jar